#!/bin/bash

# Set default username and password
username="user"
password="root"

# Set default CRP value
CRP=""

# Set default Pin value
Pin="123456"

# Set default Autostart value
Autostart=true

echo "Creating User and Setting it up"
sudo useradd -m "$username"
sudo usermod -aG wheel "$username"  # Adding the user to the wheel group for sudo access
echo "$username:$password" | sudo chpasswd
sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
echo "User created and configured with username '$username' and password '$password'"

echo "Installing necessary packages"
sudo dnf -y update
sudo dnf -y install kde-plasma-workspace xrdp wget

echo "Setting up Chrome Remote Desktop"
echo "Installing Chrome Remote Desktop"
wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
sudo dnf install -y alien
sudo alien --to-rpm chrome-remote-desktop_current_amd64.deb
sudo dnf install -y chrome-remote-desktop_current_amd64.rpm
sudo dnf install --assumeyes --fix-broken

echo "Installing Desktop Environment"
export DEBIAN_FRONTEND=noninteractive
sudo dnf groupinstall -y "KDE Plasma Workspaces"
echo "exec /usr/bin/startkde" | sudo tee /etc/chrome-remote-desktop-session
sudo systemctl disable lightdm.service

echo "Installing Google Chrome"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dnf install -y alien
sudo alien --to-rpm google-chrome-stable_current_amd64.deb
sudo dnf install -y google-chrome-stable_current_amd64.rpm
sudo dnf install --assumeyes --fix-broken

# Prompt user for CRP value
read -p "Enter CRP value: " CRP

echo "Finalizing"
if [ "$Autostart" = true ]; then
    mkdir -p "/home/$username/.config/autostart"
    link="https://youtu.be/d9ui27vVePY?si=TfVDVQOd0VHjUt_b"
    colab_autostart="[Desktop Entry]\nType=Application\nName=Colab\nExec=sh -c 'sensible-browser $link'\nIcon=\nComment=Open a predefined notebook at session signin.\nX-GNOME-Autostart-enabled=true"
    echo -e "$colab_autostart" | sudo tee "/home/$username/.config/autostart/colab.desktop"
    sudo chmod +x "/home/$username/.config/autostart/colab.desktop"
    sudo chown "$username:$username" "/home/$username/.config"
fi

sudo adduser "$username" chrome-remote-desktop
command="$CRP --pin=$Pin"
sudo su - "$username" -c "$command"
sudo service chrome-remote-desktop start

echo "Finished Successfully"
while true; do sleep 10; done
