#!/bin/bash

# Set default username and password
username="user"
password="root"

# Set default CRP value (to be provided)
CRP=""

# Set default Pin value
Pin="123456"

echo "Creating User and Setting it up..."
sudo useradd -m "$username"
sudo adduser "$username" sudo
echo "$username:$password" | sudo chpasswd
sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
echo "User '$username' created and configured."

echo "Installing Ubuntu Desktop (GNOME)..."
sudo apt update
sudo apt install -y ubuntu-desktop dbus-x11 gnome-terminal

echo "Configuring Chrome Remote Desktop..."
echo "Installing Chrome Remote Desktop..."
wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
sudo dpkg --install chrome-remote-desktop_current_amd64.deb
sudo apt install --assume-yes --fix-broken

echo "Configuring GNOME for Chrome Remote Desktop..."
echo "exec gnome-session" | sudo tee /etc/chrome-remote-desktop-session
sudo adduser "$username" chrome-remote-desktop

echo "Installing Google Chrome..."
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb
sudo apt install --assume-yes --fix-broken

# Prompt user for CRP value
read -p "Enter CRP value: " CRP

echo "Finalizing setup..."
command="$CRP --pin=$Pin"
sudo su - "$username" -c "$command"

echo "Starting Chrome Remote Desktop manually..."
sudo /opt/google/chrome-remote-desktop/start-host &

echo "Finished Successfully! Full Ubuntu Desktop (GNOME) is now ready for Chrome Remote Desktop."
while true; do sleep 10; done
