#!/bin/bash

# Set default username and password
username="user"
password="root"

# Set default CRP value (to be provided)
CRP=""

# Set default Pin value
Pin="123456"

# Set default Autostart value
Autostart=true

echo "Creating User and Setting it up..."
sudo useradd -m "$username"
sudo adduser "$username" sudo
echo "$username:$password" | sudo chpasswd
sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
echo "User '$username' created and configured."

echo "Installing necessary packages..."
sudo apt update
sudo apt install -y ubuntu-desktop chrome-remote-desktop

echo "Configuring Chrome Remote Desktop..."
echo "exec /etc/X11/Xsession gnome-session" | sudo tee /etc/chrome-remote-desktop-session
sudo adduser "$username" chrome-remote-desktop

echo "Installing Google Chrome..."
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg --install google-chrome-stable_current_amd64.deb
sudo apt install --assume-yes --fix-broken

# Prompt user for CRP value
read -p "Enter CRP value: " CRP

echo "Finalizing..."
command="$CRP --pin=$Pin"
sudo su - "$username" -c "$command"

echo "Starting Chrome Remote Desktop manually..."
sudo bash /opt/google/chrome-remote-desktop/start-host &

echo "Finished Successfully!"
while true; do sleep 10; done
