#!/bin/bash

# Set default username and password
username="user"
password="root"

echo "Creating User and Setting it up"
sudo useradd -m "$username"
sudo adduser "$username" sudo
echo "$username:$password" | sudo chpasswd
sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
echo "User created and configured with username '$username' and password '$password'"

echo "Installing necessary packages"
sudo apt update
sudo apt install -y xfce4 desktop-base xfce4-terminal wget curl

echo "Installing TurboVNC"
wget https://sourceforge.net/projects/turbovnc/files/3.0.2/turbovnc_3.0.2_amd64.deb
sudo dpkg -i turbovnc_3.0.2_amd64.deb
sudo apt install --assume-yes --fix-broken

echo "Configuring TurboVNC"
sudo -u "$username" vncserver :1 -geometry 1280x720 -depth 24
echo "exec startxfce4" > /home/$username/.vnc/xstartup
sudo chmod +x /home/$username/.vnc/xstartup
sudo chown -R "$username:$username" /home/$username/.vnc

echo "Creating a startup script for TurboVNC"
echo -e "#!/bin/bash\nvncserver :1 -geometry 1280x720 -depth 24" | sudo tee /usr/local/bin/start-vnc.sh
sudo chmod +x /usr/local/bin/start-vnc.sh

echo "Starting TurboVNC Server"
sudo -u "$username" /usr/local/bin/start-vnc.sh

echo "Setup Complete! Connect using VNC Viewer with: your-server-ip:5901"
while true; do sleep 10; done
